package manga.service;

import manga.repository.NotificationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Coordinates notification creation rules between business modules and the
 * notification repository. This service validates caller input before the
 * stored notification is created for a user.
 */
@Service
public class NotificationService {

    @Autowired
    private NotificationRepository notificationRepository;

    /**
     * Creates a notification for a target user with reference metadata.
     *
     * @param userId target user id that will receive the notification
     * @param type notification type generated by the business flow
     * @param message user-facing notification message
     * @param referenceId related entity id, or a non-positive value when absent
     * @param referenceType related entity type such as TASK, PROPOSAL, or SERIES
     * @return nothing; the notification row is created as a side effect
     */
    public void notifyUser(long userId, String type, String message, long referenceId, String referenceType) {
        if (userId <= 0) {
            throw new IllegalArgumentException("Notification target user is required");
        }
        if (isBlank(type) || isBlank(message)) {
            throw new IllegalArgumentException("Notification type and message are required");
        }
        // The repository stores the viewUrl at creation time from type/reference metadata.
        notificationRepository.create(userId, type.trim().toUpperCase(), message.trim(), referenceId, referenceType);
    }

    /**
     * Checks whether a notification with the same user/type/reference exists.
     *
     * @param userId target user id
     * @param type notification type to check
     * @param referenceId related entity id to check
     * @return {@code true} when a matching notification already exists
     */
    public boolean existsNotification(long userId, String type, long referenceId) {
        return notificationRepository.exists(userId, type, referenceId);
    }

    private boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }
}
